"""
USGS Mineral Commodity Data Loader.

Loads preprocessed USGS data from data/processed/usgs/ and prepares
datasets for the Adaptive Temporal-Structural Fusion model.

Expected preprocessed files (generated by usgs_preprocessing.py):
  data/processed/usgs/
  ├── NodesIndex.csv         ← node_id, commodity_name
  ├── Node Types.csv         ← node_id, commodity_name, category, category_name
  ├── all_edges.csv          ← source_id, target_id, edge_type_id, edge_weight
  ├── Production.csv         ← Year, 0, 1, 2, ..., N-1  (wide format)
  ├── Consumption.csv
  ├── Imports.csv
  ├── Exports.csv
  ├── Price.csv
  └── Stocks.csv

Usage:
    loader = USGSLoader(config)
    train_ds, val_ds, test_ds, info = loader.prepare_datasets()
"""

import os
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset
from torch_geometric.data import Data


# ==============================================================================
# Configuration defaults for USGS
# ==============================================================================

USGS_FEATURES = [
    "Production", "Consumption", "Imports", "Exports", "Price",
    "Stocks", "Supply", "Employment", "WorldProduction",
    "NetReliance", "NetImportReliance", "RecyclingRate",
]

EDGE_TYPE_NAMES = {
    0: "supply_chain_input",
    1: "technology_cluster",
    2: "alloy_components",
    3: "construction_coproduction",
    4: "electronics_coproduction",
    5: "substitution",
    6: "battery_coproduction",
    7: "critical_mineral_designation",
    8: "geopolitical_supply_risk",
    9: "price_correlation",
    10: "recycling_secondary_source",
    11: "byproduct_coproduction",
    12: "catalyst_role",
    13: "refractory_industrial",
    14: "functional_coating",
}


# ==============================================================================
# USGSLoader
# ==============================================================================

class USGSLoader:
    """
    USGS Mineral Commodity Data Loader — matches SupplyGraphLoader interface.

    Loads preprocessed USGS data and returns train/val/test datasets
    with the same schema as SupplyGraphLoader for seamless integration.

    Key differences from SupplyGraph:
      - YEARLY granularity (not daily)
      - 127 commodities (not 40 products)
      - 15 edge types (not 4)
      - Different feature names (Production, Consumption, etc.)
      - No day-of-week / month-of-year temporal embeddings

    Args:
        config: Configuration dictionary.
    """

    def __init__(self, config: dict) -> None:
        self.config = config
        data_cfg = config["data"]
        # In bifurcated config, data_cfg IS the usgs data block
        self.data_path = data_cfg["path"]
        self.raw_path = data_cfg["raw_path"]

        self.train_ratio = data_cfg["train_ratio"]
        self.val_ratio = data_cfg["val_ratio"]
        self.test_ratio = data_cfg["test_ratio"]
        self.seq_length = data_cfg["sequence_length"]
        self.horizons = data_cfg["forecast_horizons"]
        self.feature_names = data_cfg["features"]
        self.seed = config["reproducibility"]["seed"]

    # ------------------------------------------------------------------
    # Data loading
    # ------------------------------------------------------------------

    def load_nodes(self) -> Tuple[pd.DataFrame, pd.DataFrame]:
        """
        Load node metadata from preprocessed files.

        Returns:
            (nodes_index_df, node_types_df)
        """
        nodes_index_df = pd.read_csv(
            os.path.join(self.data_path, "NodesIndex.csv")
        )
        node_types_df = pd.read_csv(
            os.path.join(self.data_path, "Node Types.csv")
        )
        n = len(nodes_index_df)
        print(f"  [USGS] Loaded {n} commodity nodes")
        return nodes_index_df, node_types_df

    def load_edges(
        self,
    ) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor, Dict]:
        """
        Load edge data from all_edges.csv.

        Returns:
            edge_index: [2, num_edges] tensor (long)
            edge_attr:  [num_edges, num_edge_types + 1] edge features
            edge_type:  [num_edges] integer tensor (0-14)
            edge_weight: [num_edges] float tensor (0.5-1.0)
            edge_counts: Dict mapping edge type name → count
        """
        edges_df = pd.read_csv(
            os.path.join(self.data_path, "all_edges.csv")
        )

        source = edges_df["source_id"].values
        target = edges_df["target_id"].values
        e_type = edges_df["edge_type_id"].values
        e_weight = edges_df["edge_weight"].values

        edge_index = torch.tensor(
            np.stack([source, target], axis=0), dtype=torch.long
        )
        edge_type = torch.tensor(e_type, dtype=torch.long)
        edge_weight = torch.tensor(e_weight, dtype=torch.float)

        # Build edge_attr: one-hot(type) + weight
        num_edge_types = int(edge_type.max().item()) + 1
        one_hot = torch.nn.functional.one_hot(
            edge_type, num_classes=num_edge_types
        ).float()
        edge_attr = torch.cat(
            [one_hot, edge_weight.unsqueeze(-1)], dim=-1
        )

        # Edge counts
        edge_counts = {}
        for t_id in range(num_edge_types):
            name = EDGE_TYPE_NAMES.get(t_id, f"type_{t_id}")
            edge_counts[name] = int((edge_type == t_id).sum().item())

        n_edges = edge_index.shape[1]
        print(f"  [USGS] Loaded {n_edges} edges ({num_edge_types} types)")
        return edge_index, edge_attr, edge_type, edge_weight, edge_counts

    def load_temporal_data(self) -> Tuple[Dict[str, pd.DataFrame], List[int]]:
        """
        Load all temporal feature CSVs (wide format).

        Returns:
            temporal_data: Dict[feature_name → DataFrame]
            years: sorted list of years
        """
        temporal_data = {}
        years = None

        for feat_name in self.feature_names:
            csv_path = os.path.join(self.data_path, f"{feat_name}.csv")
            if not os.path.exists(csv_path):
                print(f"  [USGS] [WARN] {feat_name}.csv not found, skipping")
                continue
            df = pd.read_csv(csv_path)
            temporal_data[feat_name] = df
            if years is None:
                years = sorted(df["Year"].astype(int).tolist())

        if years is None:
            raise FileNotFoundError(
                f"No temporal feature files found in {self.data_path}"
            )

        print(f"  [USGS] Loaded {len(temporal_data)} temporal features")
        print(f"  [USGS] Years: {min(years)}-{max(years)} ({len(years)} years)")
        return temporal_data, years

    def build_feature_matrix(
        self,
        temporal_data: Dict[str, pd.DataFrame],
        n_nodes: int,
        years: List[int],
    ) -> Tuple[np.ndarray, np.ndarray]:
        """
        Build feature and demand matrices from temporal data.

        Returns:
            feature_matrix: [n_nodes, n_timepoints, n_features] array
            demand_matrix:  [n_nodes, n_timepoints] array
                            (uses Production as demand proxy, normalized per-node)
            target_means:   [n_nodes] array of unscaled means
            target_stds:    [n_nodes] array of unscaled standard deviations
        """
        n_timepoints = len(years)
        feature_names_present = list(temporal_data.keys())
        n_features = len(feature_names_present)

        feature_matrix = np.zeros(
            (n_nodes, n_timepoints, n_features), dtype=np.float32
        )

        for f_idx, feat_name in enumerate(feature_names_present):
            df = temporal_data[feat_name]
            # Drop Year column, remaining columns are node IDs as strings
            for t_idx, year in enumerate(years):
                row = df[df["Year"] == year]
                if len(row) == 0:
                    continue
                for nid in range(n_nodes):
                    col = str(nid)
                    if col in row.columns:
                        val = row[col].values[0]
                        if not np.isnan(val):
                            feature_matrix[nid, t_idx, f_idx] = val

        # Demand matrix: use Production (first feature) as demand proxy
        demand_matrix = feature_matrix[:, :, 0].copy()

        # Target Normalization (Per-Node Z-Score) for stable optimization
        target_means = demand_matrix.mean(axis=1)
        target_stds = demand_matrix.std(axis=1)
        target_stds_safe = np.where(target_stds == 0, 1.0, target_stds)
        demand_matrix = (demand_matrix.T - target_means).T / target_stds_safe[:, np.newaxis]

        # ---- Per-node per-feature Z-score normalization (Issue 19/8) ----
        # Consistent with SupplyGraphLoader for cross-task methodological fairness
        feature_means = feature_matrix.mean(axis=1, keepdims=True)
        feature_stds  = feature_matrix.std(axis=1, keepdims=True)
        feature_stds_safe = np.where(feature_stds < 1e-8, 1.0, feature_stds)
        feature_matrix = (feature_matrix - feature_means) / feature_stds_safe
        
        # Robust clipping for extreme volatility in mineral prices/trade
        feature_matrix = np.clip(feature_matrix, -5.0, 5.0)

        print(f"  [USGS] Feature/Demand matrices normalized and clipped.")
        return feature_matrix, demand_matrix, target_means, target_stds

    def build_node_features(
        self,
        feature_matrix: np.ndarray,
        demand_matrix: np.ndarray,
        node_types_df: pd.DataFrame,
        n_nodes: int,
    ) -> Tuple[torch.Tensor, torch.Tensor, Dict[str, Any]]:
        """
        Build node feature tensor for GAT branch.

        Uses StaticNodeFeatures.csv if available (11 rich features),
        otherwise falls back to 4 basic computed features.

        Returns:
            node_features: [n_nodes, N] tensor
            material_types: [n_nodes] tensor (category IDs)
            metadata: dict with lead_times, n_material_types
        """
        n_features = feature_matrix.shape[2]
        n_timepoints = feature_matrix.shape[1]

        # Try to load rich static features from preprocessing stage 4
        static_path = os.path.join(self.data_path, "StaticNodeFeatures.csv")
        if os.path.exists(static_path):
            static_df = pd.read_csv(static_path)
            static_cols = [
                "net_import_reliance", "price_cagr_5yr",
                "consumption_trend_5yr", "supply_concentration",
                "n_end_uses", "world_production", "is_critical_mineral",
                "scrap_recycling_rate", "domestic_value_rank",
                "export_control_risk", "trade_agreement_coverage",
            ]
            # Build node features from static file
            node_feats = np.zeros((n_nodes, len(static_cols)), dtype=np.float32)
            for i, col in enumerate(static_cols):
                if col in static_df.columns:
                    vals = pd.to_numeric(static_df[col], errors="coerce").fillna(0).values
                    if len(vals) == n_nodes:
                        node_feats[:, i] = vals[:n_nodes]

            # Z-score normalize each feature
            for f in range(node_feats.shape[1]):
                col = node_feats[:, f]
                std = col.std()
                if std > 0:
                    node_feats[:, f] = (col - col.mean()) / std

            node_features = torch.tensor(node_feats, dtype=torch.float)
            print(f"  [USGS] Node features: {node_features.shape} (from StaticNodeFeatures.csv)")
        else:
            # Fallback: compute 4 basic features
            node_feats = np.zeros((n_nodes, 4), dtype=np.float32)
            for nid in range(n_nodes):
                lookback = min(2, n_timepoints)
                node_feats[nid, 0] = demand_matrix[nid, -lookback:].mean()
                if n_features > 4:
                    price_series = feature_matrix[nid, :, 4]
                    mean_price = price_series.mean()
                    node_feats[nid, 1] = price_series[-1] / mean_price if mean_price > 0 else 1.0
                else:
                    node_feats[nid, 1] = 1.0
                node_feats[nid, 2] = demand_matrix[nid, -1]
                cat = node_types_df.loc[node_types_df["node_id"] == nid, "category"]
                node_feats[nid, 3] = cat.values[0] / 8.0 if len(cat) > 0 else 0.0
            for f in range(4):
                col = node_feats[:, f]
                std = col.std()
                if std > 0:
                    node_feats[:, f] = (col - col.mean()) / std
            node_features = torch.tensor(node_feats, dtype=torch.float)
            print(f"  [USGS] Node features: {node_features.shape} (basic fallback)")

        # Material types
        material_types = torch.zeros(n_nodes, dtype=torch.long)
        for nid in range(n_nodes):
            cat = node_types_df.loc[
                node_types_df["node_id"] == nid, "category"
            ]
            if len(cat) > 0:
                material_types[nid] = int(cat.values[0])

        n_material_types = int(material_types.max().item()) + 1

        # Synthetic lead times (USGS doesn't have lead time data)
        lead_times = np.ones(n_nodes, dtype=np.float32)

        metadata = {
            "lead_times": lead_times,
            "n_material_types": n_material_types,
        }

        print(f"  [USGS] Material types: {n_material_types} categories")
        return node_features, material_types, metadata

    def build_static_features(
        self,
        material_types: torch.Tensor,
        lead_times: np.ndarray,
        n_nodes: int,
    ) -> np.ndarray:
        """
        Build static features for TFT branch.

        Static features (2 per node):
          - material_type (integer, for embedding)
          - avg_lead_time (normalized)

        Returns:
            static_features: [n_nodes, 2] array
        """
        static = np.zeros((n_nodes, 2), dtype=np.float32)
        # Bypassing GCP's "RuntimeError: Numpy is not available" by converting to python list first
        static[:, 0] = np.array(material_types.tolist(), dtype=np.float32)
        static[:, 1] = lead_times
        return static

    # ------------------------------------------------------------------
    # Main entry point
    # ------------------------------------------------------------------

    def prepare_datasets(
        self,
    ) -> Tuple[Any, Any, Any, Dict[str, Any]]:
        """
        Load all USGS data, build graph, create Train/Val/Test datasets.

        Returns:
            (train_dataset, val_dataset, test_dataset, info_dict)

            info_dict matches SupplyGraphLoader schema:
              - graph_data: PyTorch Geometric Data object
              - n_nodes: number of nodes
              - n_timepoints: number of timepoints
              - n_features: number of temporal features
              - feature_names: list of feature names
              - node_names: list of commodity names
              - metadata: lead_times, n_material_types, etc.
              - edge_counts: Dict of edge type → count
        """
        print("\n" + "=" * 60)
        print("  LOADING USGS MINERAL COMMODITY DATASET")
        print("=" * 60)

        # Step 1: Load nodes
        nodes_index_df, node_types_df = self.load_nodes()
        n_nodes = len(nodes_index_df)
        node_names = nodes_index_df["commodity_name"].tolist()

        # Step 2: Load edges
        edge_index, edge_attr, edge_type, edge_weight, edge_counts = (
            self.load_edges()
        )

        # Step 3: Load temporal data
        temporal_data, years = self.load_temporal_data()
        n_timepoints = len(years)

        # Step 4: Build feature matrices
        feature_matrix, demand_matrix, target_means, target_stds = self.build_feature_matrix(
            temporal_data, n_nodes, years
        )

        # Step 5: Build node features
        node_features, material_types, metadata = self.build_node_features(
            feature_matrix, demand_matrix, node_types_df, n_nodes
        )

        # Step 6: Build static features (synchronize with GAT rich features)
        static_features = node_features.numpy()

        # Step 7: Construct PyTorch Geometric Data object
        num_edge_types = int(edge_type.max().item()) + 1

        graph_data = Data(
            x=node_features,
            edge_index=edge_index,
            edge_attr=edge_attr,
            num_nodes=n_nodes,
        )
        graph_data.material_types = material_types
        graph_data.lead_times = torch.tensor(
            metadata["lead_times"], dtype=torch.float
        )
        # USGS-specific: edge_type and edge_weight on graph
        graph_data.edge_type = edge_type
        graph_data.edge_weight_values = edge_weight
        graph_data.num_edge_types = num_edge_types

        # --- Injected Scaling Stats for Inverse Transform ---
        graph_data.target_means = torch.tensor(target_means, dtype=torch.float)
        graph_data.target_stds = torch.tensor(target_stds, dtype=torch.float)

        # Step 8: Smart chronological train/val/test split
        # For small datasets, standard ratio-based splitting may produce
        # empty sets. We compute valid sample positions first, then split.
        max_horizon = max(self.horizons)
        first_valid = self.seq_length  # first position that has enough history
        last_valid = n_timepoints - max_horizon  # last position that has target

        n_valid_positions = last_valid - first_valid
        print(f"\n  [USGS] Valid sample positions: {first_valid} to {last_valid - 1}"
              f" ({n_valid_positions} positions)")

        if n_valid_positions <= 0:
            raise ValueError(
                f"Not enough timepoints! seq_length={self.seq_length}, "
                f"max_horizon={max_horizon}, n_timepoints={n_timepoints}. "
                f"Need at least {self.seq_length + max_horizon + 1} timepoints."
            )

        # ======================================================================
        # [MODIFIED BY ANTIGRAVITY] 
        # WHERE: Here in the Data Split logic of prepare_datasets()
        # WHY: IEEE baseline requires robust evaluation on extremely short 
        #      time-series (USGS has only 5 years). A static chronological 
        #      split (e.g., train on 2021-2023, test on 2024) wastes data and 
        #      gives statistically weak results. Leave-One-Out CV causes 
        #      "time leakage" (training on future data to predict the past).
        # HOW IT WORKS: "Rolling Window Walk-Forward CV". 
        #      Fold 1: Train on years [2021-2023], Test on [2024]
        #      Fold 2: Train on years [2021-2024], Test on [2025]
        #      We dynamically select the test_pos based on the cv_fold config
        #      and use all positions *before* test_pos for training.
        # ======================================================================
        usgs_data_cfg = self.config.get("data", {})
        rolling_cv = usgs_data_cfg.get("rolling_window_cv", False)
        if rolling_cv and n_valid_positions >= 2:
            n_folds = usgs_data_cfg.get("n_cv_folds", 2)
            cv_fold = usgs_data_cfg.get("cv_fold", 1)
            cv_fold = max(1, min(cv_fold, n_folds))

            test_pos = last_valid - n_folds + cv_fold - 1
            train_positions = list(range(first_valid, test_pos))
            val_positions = [test_pos]
            test_positions = [test_pos]
            print(f"  [USGS] Rolling Window CV (Fold {cv_fold}/{n_folds}) selected.")
        else:
            # Original fallback logic

            if n_valid_positions >= 3:
                # Enough for proper train/val/test split
                n_train = max(1, int(n_valid_positions * self.train_ratio))
                n_val = max(1, int(n_valid_positions * self.val_ratio))
                n_test = max(1, n_valid_positions - n_train - n_val)
    
                train_positions = list(range(first_valid, first_valid + n_train))
                val_positions = list(range(first_valid + n_train, first_valid + n_train + n_val))
                test_positions = list(range(first_valid + n_train + n_val, last_valid))
            elif n_valid_positions == 2:
                # Minimal: 1 for train, 1 for val/test (shared)
                train_positions = [first_valid]
                val_positions = [first_valid + 1]
                test_positions = [first_valid + 1]  # shared with val
            else:
                # Only 1 position — use for all (edge case)
                train_positions = [first_valid]
                val_positions = [first_valid]
                test_positions = [first_valid]

        print(f"  [USGS] Split: train={len(train_positions)} positions, "
              f"val={len(val_positions)}, test={len(test_positions)}")
        if years:
            print(f"    Train years: {[years[p] for p in train_positions]}")
            print(f"    Val years:   {[years[p] for p in val_positions]}")
            print(f"    Test years:  {[years[p] for p in test_positions]}")

        # Step 9: Create datasets using explicit position lists
        train_dataset = USGSDataset(
            feature_matrix=feature_matrix,
            demand_matrix=demand_matrix,
            static_features=static_features,
            graph_data=graph_data,
            seq_length=self.seq_length,
            horizons=self.horizons,
            valid_positions=train_positions,
            seed=self.seed,
        )
        val_dataset = USGSDataset(
            feature_matrix=feature_matrix,
            demand_matrix=demand_matrix,
            static_features=static_features,
            graph_data=graph_data,
            seq_length=self.seq_length,
            horizons=self.horizons,
            valid_positions=val_positions,
            seed=self.seed,
        )
        test_dataset = USGSDataset(
            feature_matrix=feature_matrix,
            demand_matrix=demand_matrix,
            static_features=static_features,
            graph_data=graph_data,
            seq_length=self.seq_length,
            horizons=self.horizons,
            valid_positions=test_positions,
            seed=self.seed,
        )

        info = {
            "graph_data": graph_data,
            "n_nodes": n_nodes,
            "n_timepoints": n_timepoints,
            "n_features": feature_matrix.shape[2],
            "feature_names": list(temporal_data.keys()),
            "node_names": node_names,
            "years": years,
            "metadata": metadata,
            "edge_counts": edge_counts,
            "num_edge_types": num_edge_types,
        }

        print(f"\n  [USGS] Dataset sizes:")
        print(f"    Train: {len(train_dataset)} samples")
        print(f"    Val:   {len(val_dataset)} samples")
        print(f"    Test:  {len(test_dataset)} samples")
        print("=" * 60 + "\n")

        return train_dataset, val_dataset, test_dataset, info


# ==============================================================================
# USGSDataset
# ==============================================================================

class USGSDataset(Dataset):
    """
    PyTorch Dataset for windowed time-series from USGS.

    Same interface as SupplyGraphDataset for compatibility.
    Each sample returns:
      - time_series:     [seq_length, n_features]
      - price_history:   [seq_length]
      - static_features: [n_static]
      - targets:         [n_horizons]
      - material_type:   int
      - product_id:      int
      - horizon:         int

    Args:
        feature_matrix: [n_nodes, n_timepoints, n_features]
        demand_matrix:  [n_nodes, n_timepoints]
        static_features: [n_nodes, n_static]
        graph_data: PyTorch Geometric Data object
        seq_length: lookback window size
        horizons: list of forecast horizons
        start_idx: start of time window
        end_idx: end of time window
        seed: random seed
    """

    def __init__(
        self,
        feature_matrix: np.ndarray,
        demand_matrix: np.ndarray,
        static_features: np.ndarray,
        graph_data,
        seq_length: int,
        horizons: List[int],
        valid_positions: List[int],
        seed: int = 42,
    ) -> None:
        super().__init__()
        self.feature_matrix = feature_matrix
        self.demand_matrix = demand_matrix
        self.static_features = static_features
        self.graph_data = graph_data
        self.seq_length = seq_length
        self.horizons = horizons
        self.max_horizon = max(horizons) if horizons else 1
        self.seed = seed

        n_nodes = feature_matrix.shape[0]

        # Build sample list: (commodity_id, time_idx) for all valid positions
        self.samples: List[Tuple[int, int]] = []

        for nid in range(n_nodes):
            for t in valid_positions:
                self.samples.append((nid, t))

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, idx: int) -> Dict[str, torch.Tensor]:
        nid, t = self.samples[idx]

        # ---- Time series features [seq_length, n_features] ----
        time_series = self.feature_matrix[nid, t - self.seq_length : t, :]

        # ---- Price/demand history [seq_length] ----
        price_history = self.demand_matrix[nid, t - self.seq_length : t]

        # ---- Static features [n_static] ----
        static = self.static_features[nid]

        # ---- Targets at each horizon ----
        targets = np.array(
            [self.demand_matrix[nid, t + h] for h in self.horizons],
            dtype=np.float32,
        )

        # ---- Material type ----
        material_type = int(self.graph_data.material_types[nid].item())

        return {
            "time_series": torch.tensor(time_series, dtype=torch.float),
            "price_history": torch.tensor(price_history, dtype=torch.float),
            "static_features": torch.tensor(static, dtype=torch.float),
            "targets": torch.tensor(targets, dtype=torch.float),
            "material_type": torch.tensor(material_type, dtype=torch.long),
            "product_id": torch.tensor(nid, dtype=torch.long),
            "horizon": torch.tensor(idx % len(self.horizons), dtype=torch.long),
        }
